// Generated by scripts/trace-wordmark.mjs from public/logo-max-white.png.
// Do not edit by hand; re-run the script if the logo changes.

export const MAX_VIEWBOX = "0 0 592 163";

export const MAX_PATHS = {
  m: "M1 0L38 0L111 75L185 0L224 0L224 123L183 123L182 61L112 134L43 63L42 123L1 123Z",
  a: "M306 0L345 1L405 123L358 123L326 61L294 123L248 123L248 119Z",
  x: "M429 0L486 0L512 28L539 0L591 0L591 5L541 58L583 103L583 162L568 148L513 89L481 122L427 122L427 118L484 58Z",
} as const;
